services:
  # ======================================================================
  # Nats Server
  # ======================================================================
  nats-server:
    image: nats
    ports:
      - 8222:8222

  # ======================================================================
  # Client Gateway
  # ======================================================================
  client-gateway:
    build: ./gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    volumes:
      - ./gateway/src:/usr/src/app/src
    command: npm run dev
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  # ======================================================================
  # Products Microservice
  # ======================================================================
  products-ms:
    build: ./products
    volumes:
      - ./products/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${PRODUCTS_MS_DATABASE_URL}

  # ======================================================================
  # Orders Microservice Database
  # ======================================================================
  orders-db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=orders
      - POSTGRES_PASSWORD=12345
    volumes:
      - ./orders/postgres:/var/lib/postgresql/data

  # ======================================================================
  # Orders Microservice
  # ======================================================================
  orders-ms:
    build: ./orders
    volumes:
      - ./orders/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_MS_DATABASE_URL}
    depends_on:
      - orders-db

  # ======================================================================
  # Payments Microservice
  # ======================================================================
  payments-ms:
    build: ./payments
    volumes:
      - ./payments/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET_KEY=${PAYMENTS_MS_STRIPE_SECRET_KEY}
      - STRIPE_SUCCESS_URL=${PAYMENTS_MS_STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${PAYMENTS_MS_STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${PAYMENTS_MS_STRIPE_ENDPOINT_SECRET}

  # ======================================================================
  # Auth Microservice
  # ======================================================================
  auth-ms:
    build: ./auth
    volumes:
      - ./auth/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_MS_DATABASE_URL}
      - JWT_SECRET_KEY=${AUTH_MS_JWT_SECRET_KEY}
