services:
  # ======================================================================
  # Nats Server
  # ======================================================================
  nats-server:
    image: nats

  # ======================================================================
  # Client Gateway
  # ======================================================================
  client-gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/nestjs-microservices-458108/docker-registry/client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  # ======================================================================
  # Products Microservice
  # ======================================================================
  products-ms:
    build:
      context: ./products
      dockerfile: Dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/nestjs-microservices-458108/docker-registry/products-ms
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${PRODUCTS_MS_DATABASE_URL}

  # ======================================================================
  # Payments Microservice
  # ======================================================================
  payments-ms:
    build:
      context: ./payments
      dockerfile: Dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/nestjs-microservices-458108/docker-registry/payments-ms
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET_KEY=${PAYMENTS_MS_STRIPE_SECRET_KEY}
      - STRIPE_SUCCESS_URL=${PAYMENTS_MS_STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${PAYMENTS_MS_STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${PAYMENTS_MS_STRIPE_ENDPOINT_SECRET}

  # ======================================================================
  # Orders Microservice
  # ======================================================================
  orders-ms:
    build:
      context: ./orders
      dockerfile: Dockerfile.prod
      args:
        - ORDERS_MS_DATABASE_URL=${ORDERS_MS_DATABASE_URL}
    image: northamerica-south1-docker.pkg.dev/nestjs-microservices-458108/docker-registry/orders-ms
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_MS_DATABASE_URL}

  # ======================================================================
  # Auth Microservice
  # ======================================================================
  auth-ms:
    build:
      context: ./auth
      dockerfile: Dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/nestjs-microservices-458108/docker-registry/auth-ms
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_MS_DATABASE_URL}
      - JWT_SECRET_KEY=${AUTH_MS_JWT_SECRET_KEY}
